name: codequiz
description: "CodeQuiz - Application mobile d'évaluation de niveau en programmation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  sqflite: ^2.3.3
  path: ^1.9.0
  crypto: ^3.0.3
  fl_chart: ^0.69.0
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  pdf: ^3.11.1
  share_plus: ^10.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
